[package]
name = "vanguard_os"
version = "0.2.0"
edition = "2021"

[dependencies]
# Графический движок для высокоскоростного рендеринга окон и Canvas на видеокарте
eframe = "0.28"
# Сбор метрик процессора, оперативной памяти и жестких дисков (вместо psutil)
sysinfo = "0.30"
# Поиск файлов на жестком диске по маске (вместо glob)
glob = "0.3"
# Безопасный расчет хэш-сумм для проверки целостности файлов ядра (вместо hashlib)
md5 = "0.7"
# Локальный генератор случайных чисел для частиц взрыва и глитчей (вместо random)
rand = "0.8"
# Скрытый ввод пароля в терминале без отображения символов (вместо getpass)
rpassword = "7.3"
# Форматирование и вывод живого системного времени и даты (вместо time.strftime)
chrono = "0.4"
# Быстрый многострочный парсинг ИИ-кода с защитой от зависаний (вместо re)
regex = "1.10"
